name: 'Set up R package'
description: 'Install pandoc, system dependencies, and the R package dependencies'
author: 'Barret Schloerke'
inputs:
  r-version:
    default: "release"
    description: R version to be installed
    required: false
  http-user-agent:
    default: ""
    description: HTTP user agent to be sent to RSPM
    required: false
  needs:
    default: ""
    description: "Name of config to search in `DESCRIPTION` file. Ex: `website`"
    required: false
  extra-packages:
    default: ""
    description: Extra packages to be installed
    required: false
  cache-version:
    default: "1"
    description: Value to be inserted into the cache key
    required: false
  pandoc-version:
    default: "3.x"
    description: Pandoc version to be installed
    required: false
  packages:
    default: "local::., deps::., any::sessioninfo"
    description: Packages to install
    required: false
  rtools-version:
    default: ""
    description: 'Exact version of Rtools to use. Default uses latest suitable rtools for the given version of R. Set it to "42" for Rtools42.'
    required: false
# outputs:
#   NAME:
#     description: 'desc here'
#     value: ${{ steps.ID.outputs.OUT_ID }}

runs:
  using: "composite"
  steps:

    - name: Pandoc version
      id: pandoc
      shell: Rscript {0}
      run: |
        # Get corresponding pandoc version
        pandoc_version <- "${{ inputs.pandoc-version }}"
        switch(pandoc_version,
          "default" =,
          "3.x" = "3.1.2",
          "2.x" = "2.19.2",
          pandoc_version
        )
        cat("version=", pandoc_version, \n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)

    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: ${{ steps.pandoc.outputs.version }}

    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ inputs.r-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        rtools-version: ${{ inputs.rtools-version }}
        use-public-rspm: true

    - uses: rstudio/shiny-workflows/setup-macOS-dependencies@v1
      with:
        needs: ${{ inputs.needs }}
        extra-packages: ${{ inputs.extra-packages }}

    - name: Run 'package-install' script
      uses: rstudio/shiny-workflows/.github/internal/run-local-script@v1
      with:
        name: package-install

    # - uses: r-lib/actions/setup-r-dependencies@v2
    # TODO-fix to v1!
    - uses: schloerke/actions/setup-r-dependencies@always_cache_r_lib
      with:
        cache: "always"
        packages: ${{ inputs.packages }}
        cache-version: ${{ inputs.needs }}-${{ inputs.cache-version }}
        needs: ${{ inputs.needs }}
        extra-packages:
          any::sessioninfo
          ${{ inputs.extra-packages }}

    - name: Install phantomJS
      uses: rstudio/shiny-workflows/setup-phantomjs@v1
      with:
        cache-version: ${{ inputs.cache-version }}
    - name: Install tinytex
      uses: rstudio/shiny-workflows/setup-tinytex@v1
