// Regenerate the managed block of a `LICENSE.note` file from the direct
// production dependencies listed in `package.json`.
//
// Usage:
//   node license-note.mjs [--root <dir>] [--js-dir <dir>] [--path LICENSE.note] [--check]
//
// `--path` and `--js-dir` are resolved against `--root` (the repository root),
// so this does not care what directory it is invoked from.
//
// Only the region between the `BEGIN`/`END` marker lines is touched; everything
// else in the file is left exactly as-is. If the file does not exist, or does
// not contain a `BEGIN` marker, nothing is written: adding the markers is how a
// repo opts in.
//
// Background on why this file exists at all:
// https://r-pkgs.org/license.html#sec-code-you-bundle

import fs from "node:fs";
import path from "node:path";

const BEGIN_MARKER = "### BEGIN bundled JavaScript dependencies";
const END_MARKER = "### END bundled JavaScript dependencies";
const BEGIN_LINE = `${BEGIN_MARKER} (generated by rstudio/shiny-workflows)`;
const END_LINE = END_MARKER;

const LICENSE_FILE_PATTERN = /^(licen[cs]e|copying|unlicen[cs]e)(\..*)?$/i;

function parseArgs(argv) {
  const args = {
    root: process.env.GITHUB_WORKSPACE || process.cwd(),
    jsDir: ".",
    notePath: "LICENSE.note",
    check: false,
  };
  for (let i = 0; i < argv.length; i++) {
    switch (argv[i]) {
      case "--root":
        args.root = argv[++i];
        break;
      case "--js-dir":
        args.jsDir = argv[++i];
        break;
      case "--path":
        args.notePath = argv[++i];
        break;
      case "--check":
        args.check = true;
        break;
      default:
        throw new Error(`Unknown argument: ${argv[i]}`);
    }
  }
  args.root = path.resolve(args.root);
  args.jsDir = path.resolve(args.root, args.jsDir);
  args.notePath = path.resolve(args.root, args.notePath);
  return args;
}

// Paths are absolute internally; report them relative to the repo root so log
// messages match what a reader sees in the repository.
function display(root, target) {
  const relative = path.relative(root, target);
  return relative === "" ? "." : relative;
}

// GitHub Actions workflow commands. Safe no-ops when run locally.
function notice(message) {
  console.log(`::notice::${message}`);
}
function warn(message) {
  console.log(`::warning::${message}`);
}
function fail(message) {
  console.log(`::error::${message}`);
  process.exit(1);
}

// Walk up from `startDir` looking for `node_modules/<name>`, so that hoisted
// installs (a monorepo root, or `js-working-directory` nested inside the
// package) resolve the same way node itself would. The walk stops at the
// repository root: reaching past it would resolve against whatever the runner
// happens to have installed outside the checkout.
function findPackageDir(name, startDir, root) {
  let dir = startDir;
  for (;;) {
    const candidate = path.join(dir, "node_modules", name);
    if (fs.existsSync(path.join(candidate, "package.json"))) return candidate;
    if (dir === root) return null;
    const parent = path.dirname(dir);
    if (parent === dir) return null;
    dir = parent;
  }
}

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

// `license` is the modern field; `licenses` is the deprecated array form still
// used by a handful of long-lived packages.
function licenseId(pkg) {
  if (typeof pkg.license === "string") return pkg.license;
  if (pkg.license && typeof pkg.license.type === "string") return pkg.license.type;
  if (Array.isArray(pkg.licenses)) {
    const ids = pkg.licenses.map((l) => (typeof l === "string" ? l : l.type)).filter(Boolean);
    if (ids.length > 0) return ids.join(" OR ");
  }
  return null;
}

function repositoryUrl(pkg) {
  const repo = pkg.repository;
  let url = typeof repo === "string" ? repo : repo && repo.url;
  if (!url) return pkg.homepage || null;
  // Normalize the many shorthand forms npm allows into a browsable https URL.
  url = url
    .replace(/^git\+/, "")
    .replace(/\.git$/, "")
    .replace(/^git:\/\//, "https://")
    .replace(/^ssh:\/\/git@/, "https://")
    .replace(/^git@([^:]+):/, "https://$1/");
  if (!/^https?:\/\//.test(url)) url = `https://github.com/${url}`;
  return url;
}

function licenseFile(pkgDir) {
  const match = fs
    .readdirSync(pkgDir)
    .filter((file) => LICENSE_FILE_PATTERN.test(file))
    .sort();
  return match.length > 0 ? path.join(pkgDir, match[0]) : null;
}

// Which packages actually end up bundled is something only the repo knows: the
// `dependencies` / `devDependencies` split tracks *build* roles, not shipped
// ones. A repo that bundles from `devDependencies` (or that has `@types/*`
// packages in `dependencies` that ship nothing) names its bundled packages
// explicitly via `licenseNote.bundled` in `package.json`.
function bundledNames(manifest) {
  const configured = manifest.licenseNote && manifest.licenseNote.bundled;
  if (configured) {
    if (!Array.isArray(configured)) {
      fail("'licenseNote.bundled' in package.json must be an array of package names.");
    }
    return [...configured].sort();
  }
  return Object.keys(manifest.dependencies || {}).sort();
}

function collectDependencies(jsDir, root) {
  const manifestPath = path.join(jsDir, "package.json");
  if (!fs.existsSync(manifestPath)) return null;

  const names = bundledNames(readJson(manifestPath));
  return names.map((name) => {
    const pkgDir = findPackageDir(name, jsDir, root);
    if (!pkgDir) return { name, missing: true };
    const pkg = readJson(path.join(pkgDir, "package.json"));
    const license = licenseId(pkg);
    if (!license) {
      warn(`'${name}' does not declare a license in its package.json.`);
    }
    if (!licenseFile(pkgDir)) {
      warn(`'${name}' does not ship a license file.`);
    }
    return {
      name,
      version: pkg.version,
      license: license || "UNKNOWN",
      url: repositoryUrl(pkg),
    };
  });
}

function renderBlock(deps) {
  const lines = [BEGIN_LINE, ""];
  if (deps.length === 0) {
    lines.push("(none)");
  }
  for (const dep of deps) {
    const suffix = dep.url ? ` (${dep.url})` : "";
    lines.push(`* ${dep.name}@${dep.version}: ${dep.license}${suffix}`);
  }
  lines.push("", END_LINE);
  return lines.join("\n");
}

function replaceBlock(contents, block) {
  const lines = contents.split("\n");
  const begin = lines.findIndex((line) => line.startsWith(BEGIN_MARKER));
  const end = lines.findIndex((line) => line.startsWith(END_MARKER));
  if (end < begin) {
    fail(`Found '${BEGIN_MARKER}' but no matching '${END_MARKER}' after it.`);
  }
  return [...lines.slice(0, begin), ...block.split("\n"), ...lines.slice(end + 1)].join("\n");
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const note = display(args.root, args.notePath);
  const jsDir = display(args.root, args.jsDir);

  if (!fs.existsSync(args.notePath)) {
    notice(
      `No '${note}' found; skipping. To opt in, create the file and add a '${BEGIN_MARKER}' / '${END_MARKER}' pair where the dependency list should go.`
    );
    return;
  }

  const contents = fs.readFileSync(args.notePath, "utf8");
  if (!contents.split("\n").some((line) => line.startsWith(BEGIN_MARKER))) {
    notice(
      `'${note}' has no '${BEGIN_MARKER}' marker; skipping. Add a '${BEGIN_MARKER}' / '${END_MARKER}' pair where the dependency list should go to opt in.`
    );
    return;
  }

  if (!fs.existsSync(args.jsDir)) {
    fail(`'${note}' opts in to license-note generation, but the directory '${jsDir}' does not exist.`);
  }

  const deps = collectDependencies(args.jsDir, args.root);
  if (deps === null) {
    fail(`'${note}' opts in to license-note generation, but no 'package.json' was found in '${jsDir}'.`);
  }

  // Bail rather than write a list that silently omits real licenses.
  const missing = deps.filter((dep) => dep.missing).map((dep) => dep.name);
  if (missing.length > 0) {
    fail(
      `Could not find ${missing.join(", ")} in '${jsDir}/node_modules'. Install the JavaScript dependencies before running this action.`
    );
  }

  const updated = replaceBlock(contents, renderBlock(deps));
  if (updated === contents) {
    console.log(`'${note}' is up to date.`);
    return;
  }

  if (args.check) {
    fail(`'${note}' is out of date. Run the 'routine' workflow to regenerate it.`);
  }

  fs.writeFileSync(args.notePath, updated);
  console.log(`Updated '${note}'.`);

  // Lets the action decide whether to leave a PR comment.
  if (process.env.GITHUB_OUTPUT) {
    fs.appendFileSync(process.env.GITHUB_OUTPUT, "updated=true\n");
  }
}

main();
